### PR TITLE
added data from sms for Leipzig, Dresden, Chemnitz

### PR DESCRIPTION
**Pull request by gerbsen**
Added inidiviudal files for 3 largest cities in saxony

### CODE REVIEW

**Comment by psteinb** [comment]
That is just lovely data! Thanks a million. 
Sorry to be a pain though, could you rename these files e.g. like `de_dresden_sms.csv`?

**Comment by gerbsen** [comment]
done

**Comment by psteinb** [comment]
f7c6620 induced a copy, not a rename. Would it be ok, if I take this PR from here?

**Comment by gerbsen** [comment]
ups, sorry. plz do so.

**Comment by psteinb** [comment]
Thanks for this great contribution.

**Pull request merged**
